name: Demo CICD
run-name: Upload to app distribution
on: [push]
jobs:
  Upload_to_App_Distribution:
    runs-on: cimg/android:2023.10
    steps:
      - run: ./gradlew assembleDebug appDistributionUploadDebug
